FROM node:alpine as build

COPY package.json package.json
RUN npm install
COPY . .
RUN npm build

FROM nginx:stable-appine

COPY --from=build /dist /usr/share/nginx/html
COPY --from=build nginx.conf /ect/nginx/conf.d/default.conf
EXPOSE 3000


CMD ["nginx", "-g", "daemon off;"]